title: Dog Hair and Toe Nails
email: doghairandtoenails@gmail.com
description: The lint that is rattling around in Camerons head.
baseurl: "" 
url: "https://doghairandtoenails.github.io" 

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  documentation:
    permalink: "/:collection/:path/"
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
